Enhance bootstrap script with improved logging and dry-run functionality

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,22 +1,86 @@
 #!/usr/bin/env bash
 
-# DOTFILES_ROOT=$(dirname "${BASH_SOURCE[0]:-$0}")
 DOTFILES_ROOT=$(cd "$(dirname "${BASH_SOURCE:-$0}")"; pwd -P)
 
 set -e
 
+# ----------------------
+# Config
+# ----------------------
+
+DRYRUN=false
+TARGET="all"
+
+# ----------------------
+# Logging
+# ----------------------
+
+WHITE=$'\e[1;37m'
 RED=$'\e[1;31m'
 GREEN=$'\e[1;32m'
+GRAY=$'\e[0;37m'
+PURPLE=$'\e[1;34m'
 
-fail () {
-  printf "\n${RED}[ FAIL ] %s\n" "$1"
-  echo ""
-  exit 1
+BOLD="\033[4;37m"
+RESET="\033[0m"
+
+_alert () {
+  local _color
+  local _label
+  local _alertType="${1}"
+  local _message="${2}"
+  local _line="${3:-}" # Optional line number
+
+  if [[ "${_alertType}" == "error" ]]; then
+    _color="${RED}"
+    _label="ERROR"
+  elif [[ "${_alertType}" == "header" ]]; then
+    _color="${BOLD}${WHITE}"
+    _label="*"
+  elif [[ "${_alertType}" == "info" ]]; then
+    _color="${GRAY}"
+    _label="INFO"
+  elif [[ "${_alertType}" == "success" ]]; then
+    _color="${GREEN}"
+    _label="SUCCESS"
+  elif [[ "${_alertType}" == "dryrun" ]]; then
+    _color="${PURPLE}"
+    _label="DRYRUN"
+  fi
+
+  printf "\n${_color}[${_label}] %s${RESET}\n" "$_message"
 }
 
-success () {
-  printf "\n${GREEN}[ OK ] %s\n" "$1"
-  echo ""
+error () {
+  _alert error "$1"
+  exit 1
+}
+header () { _alert header "$1"; }
+info () { _alert info "$1"; }
+success () { _alert success "$1"; }
+dryrun () { _alert dryrun "$1"; }
+
+
+# ----------------------
+# Parse options
+# ----------------------
+
+parse_args () {
+  while [[ "$#" -gt 0 ]]; do
+    case $1 in
+      -n|--dry-run)
+        DRYRUN=true
+        ;;
+      --target)
+        TARGET=$2
+        shift
+        ;;
+      *)
+        echo "Invalid option: $1" >&2
+        ;;
+    esac
+    shift
+  done
 }
 
 # ----------------------
@@ -24,12 +88,12 @@ success () {
 # ----------------------
 
 install_homebrew() {
-  echo "Setup Homebrew..."
+  header "Setup Homebrew..."
   # install homebrew
   if hash brew 2>/dev/null; then
-    echo "Homebrew is already installed"
+    info "Homebrew is already installed"
   else
-    echo "Installing Homebrew..."
+    info "Installing Homebrew..."
 
     /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
 
@@ -38,48 +102,47 @@ install_homebrew() {
 }
 
 install_packages_via_homebrew() {
-  echo "Installing packages via Homebrew..."
+  header "Installing packages via Homebrew..."
 
   if ! command -v brew >/dev/null 2>&1; then
-    echo "brew command could not be found"
+    info "brew command could not be found"
     exit
   fi
 
   if [ ! -f "$DOTFILES_ROOT/brew/Brewfile" ]; then
-    fail '.Brewfile was not found.'
+    error '.Brewfile was not found.'
   fi
 
   if [ ! -L "$HOME/.Brewfile" ]; then
-    ln -s "$DOTFILES_ROOT/brew/Brewfile" "$HOME/.Brewfile"
+    if [[ $DRYRUN == true ]]; then
+      dryrun "ln -s $DOTFILES_ROOT/brew/Brewfile $HOME/.Brewfile"
+    else
+      ln -s "$DOTFILES_ROOT/brew/Brewfile" "$HOME/.Brewfile"
+    fi
   fi
 
   HOMEBREW_BUNDLE_MAS_SKIP=$(brew bundle list --global --mas)
   export HOMEBREW_BUNDLE_MAS_SKIP
-  brew bundle install --global || true
+  if [[ $DRYRUN == true ]]; then
+    dryrun "brew bundle install --global"
+  else
+    brew bundle install --global || true
+  fi
 
   wait
   success 'Packages Installation by Homebrew'
 }
 
-setup_nodejs_tools() {
-  echo "Setup nodejs tools..."
-
-  if command volta -v &> /dev/null; then
-    echo "volta is already installed."
-    echo ""
-  else
-    echo "Install volta..."
-    curl https://get.volta.sh | bash -s -- --skip-setup
-  fi
-
-  success 'Setup nodejs tools'
-}
-
 set_default_shell() {
   if [[ $(basename "$SHELL") != "zsh" ]] && [[ "$(uname -m)" = "x86_64" ]]; then
     if [[ "$SHELL" != "/usr/local/bin/zsh" ]]; then
-      sudo bash -c 'echo "/usr/local/bin/zsh" >> /etc/shells'
-      sudo chsh -s /usr/local/bin/zsh
+      if [[ $DRYRUN == true ]]; then
+        dryrun "sudo bash -c 'echo \"/usr/local/bin/zsh\" >> /etc/shells'"
+        dryrun "sudo chsh -s /usr/local/bin/zsh"
+      else
+        sudo bash -c 'echo "/usr/local/bin/zsh" >> /etc/shells'
+        sudo chsh -s /usr/local/bin/zsh
+      fi
     fi
     success 'Setup default shell'
   fi
@@ -90,7 +153,7 @@ set_default_shell() {
 # ----------------------
 
 create_symlinks() {
-  echo "Create symlinks..."
+  header "Create symlinks..."
 
   for file in .??*
   do
@@ -104,8 +167,13 @@ create_symlinks() {
     local src="$DOTFILES_ROOT/$file"
     local dst="$HOME/$file"
 
+    if [[ $DRYRUN == true ]]; then
+      dryrun "ln -s $src $dst"
+      continue
+    fi
+
     if [[ -f "$dst" || -d "$dst" || -L "$dst" ]]; then
-      printf "File already exists."
+      info "$dst has already existed."
       continue
     fi
 
@@ -120,25 +188,27 @@ create_symlinks() {
 # Local config files
 # ----------------------
 
-create_local_config_files() {
-  local gitconfig_local="$HOME/.gitconfig.local"
-  if [ ! -f "$gitconfig_local" ]; then
-    echo "# [user]" > "$gitconfig_local"
-    echo "#   name = m-yoshiro" >> "$gitconfig_local"
-    echo "#   email = massugu.massugu@gmail.com" >> "$gitconfig_local"
-  fi
+# create_local_config_files() {
+#   local gitconfig_local="$HOME/.gitconfig.local"
+#   if [ ! -f "$gitconfig_local" ]; then
+#     info "# [user]" > "$gitconfig_local"
+#     info "#   name = m-yoshiro" >> "$gitconfig_local"
+#     info "#   email = massugu.massugu@gmail.com" >> "$gitconfig_local"
+#   fi
 
-  local zshrc_local="$HOME/.zshrc.local"
-  if [ ! -f "$zshrc_local" ]; then
-    echo "# zshrc for local configuration" > "$zshrc_local"
-  fi
-}
+#   local zshrc_local="$HOME/.zshrc.local"
+#   if [ ! -f "$zshrc_local" ]; then
+#     info "# zshrc for local configuration" > "$zshrc_local"
+#   fi
+# }
 
 # ----------------------
 # Main
 # ----------------------
 
-if [[ $1 == "all" ]] || [ -z "$1" ]; then
+parse_args "$@"
+
+if [[ $TARGET == "all" ]]; then
   install_homebrew
   install_packages_via_homebrew
 
